### ISSUE TITLE
Any chance for an updated version?

### ISSUE THREAD

**Issue by URBANsUNITED** [Alexoko12/Marlin_Config_Lotmaxx_SC-10#1]
Hi!

I am asking you for an updated version adapted to  the latest Marlin version, please.
Tried it by myself, but the printer didn't start printing. 
Heard of issues here:
#define FIL_RUNOUT_STATE true
tried
#define FIL_RUNOUT_STATE High
and
#define FIL_RUNOUT_STATE Low
But all no difference. Maybe you know more???

Before I am wasting time and you have already a new version, it would be absolutely great if you could share it.

Many thanks

URBANsUNITED

**Comment by Alexoko12** [comment]
Hey,

do you have any problems with 2.0.8 too?

I was quite busy these days, thats why I haven't printed for long time and neither flashed Marlin 2.0.9.
I can try to create the new version of the config, but I may need until end of the month to get time for that.

Hope thats okay for you.

Kind regards

**Comment by URBANsUNITED** [comment]
Hi!

Thanks for taking care!!
Yes, printing with 2.0.8 works as it should. But I wanted to upgrade directly to the latest firmware, which doesn't work.
I will look into by myself too to understand the firmware...

Please don't stress! I have a working printer, you are done, when you are done!

Many thanks in advance!!

URBANsUNITED

**Comment by ealvarezd** [comment]
Greetings .. I managed to compile version 2.0.9.2 for this printer, with the MKS interface but I have a problem; the printer sometimes has a random offset on the Y axis. Anyone have an idea why that happens?

**Comment by Alexoko12** [comment]
@URBANsUNITED
Hi,
as promised I made an updated config. Let me know if there are any issues as I haven't evaluated it myself. Flashing worked for me, but I haven't printed yet or connected to octoprint.

@ealvarezd 
Hey,
sorry for the late respond. As I haven't worked with 2.0.9.2 on my printer yet. I can't relate to this issue. If you have facebook I recommend you to ask your question in the Lotmaxx Official User Group:
https://www.facebook.com/groups/283552253000644
or the Lotmaxx 3D User Group:
https://www.facebook.com/groups/3877932692249450
I think here won't answer you many people as the stats show me, that not many people are using my configs.

As I think the main question is answered I close this issue, but feel free to open new ones.

best regards
Alexander

**Comment by Alexoko12** [comment]
@URBANsUNITED 
Hi,
as promised I made an updated config. Let me know if there are any issues as I haven't evaluated it myself. Flashing worked for me, but I haven't printed yet or connected to octoprint.

@ealvarezd 
Hey,
sorry for the late respond. As I haven't worked with 2.0.9.2 on my printer yet. I can't relate to this issue. If you have facebook I recommend you to ask your question in the Lotmaxx Official User Group:
https://www.facebook.com/groups/283552253000644
or the Lotmaxx 3D User Group:
https://www.facebook.com/groups/3877932692249450
I think here won't answer you many people as the stats show me, that not many people are using my configs.

As I think the main question is answered I close this issue, but feel free to open new ones.

best regards
Alexoko

**Comment by URBANsUNITED** [comment]
Hi Alexoko12!
I really appreciate your work. Many thanks!!!
The file flashed without any issues, but, of course a but, the Bltouch is not working.
I've activated the option, but it simply not reacting.
It never did with your firmware version. I've found another one. Very old 2.0.3.4 but there it is working.
I examined the config, but can't find the difference.

To summerice
The BLtouch is connected and working with the old firmware sourced from a Facebook group.
Whith yours the pin goes down and up while powering and then no further action. No self test or similar.

Any idea??

Thanks
URBANsUNITED

**Comment by URBANsUNITED** [comment]
Figured out!

You must change Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO_common.h

#define SERVO0_PIN                          PB2   // Enable BLTOUCH

and it is better to activate in Configuration.h

#define USE_PROBE_FOR_Z_HOMING

Thanks

URBANsUNITED

**Comment by Alexoko12** [comment]
Hey, 
thanks for sharing your solution. As I don't have BLTOUCH I can't check when it is not working.
It would be nice, if you could please test all 3 configs as they differ a bit in their definitions. So that I can be safe, that I haven't done any typo or wrong definition.

best regards
Alexoko

**Comment by URBANsUNITED** [comment]
Hi!
Sorry for being late.
I've checked your config without flashing them. 

Looks ok for me. As it is matching your wiring diagram and the original Marlin config.

#if ENABLED(LOTMAXX_BLTOUCH)
  #define SERVO0_PIN                        PB2   // Enable BLTOUCH
 #else
  #define SERVO0_PIN                        PA8   // Enable BLTOUCH
#endif

For Config < 2.0.9.2
If someone uses a  MKS PWC, he knows how to deal with the pins and is not the target group for these ready made configs, or?

Cheers

URBANsUNITED
